services:
    server:
        container_name: server
        image: nginx:stable
        ports:
            - 80:80
        volumes:
            - ..:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel-network
    
    api:
        container_name: api
        build: api
        restart: always
        command: php artisan serve
        ports:
            - 9000:8000
        volumes:
            - ..:/var/www/html
        networks:
            - laravel-network
        env_file: .env

    db:
        container_name: db
        cap_add:
            - SYS_NICE
        image: mariadb:10.6.18
        restart: always
        ports:
            - 3306:3306
        volumes:
            - ./init-db:/docker-entrypoint-initdb.d
            - ./mariadb:/var/lib/mysql
        networks:
            - laravel-network
        env_file: .env
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        healthcheck:
            test: '/usr/bin/mysql --user=root --password=${MYSQL_ROOT_PASSWORD} --execute "SHOW DATABASES;"'
            interval: 2s
            timeout: 30s
            retries: 10

    redis-server:
        image: redis:alpine
        container_name: redis-server
        restart: always
        command: redis-server
        ports:
            - 6379:6379
        networks:
            - laravel-network

    adminer:
        depends_on:
            db:
                condition: service_healthy
        container_name: adminer
        image: adminer
        restart: always
        ports:
            - 5540:5540
        networks:
            - laravel-network
        env_file: .env
        environment:
            ADMINER_DEFAULT_SERVER: ${DB_HOST}
    
networks:
    laravel-network:
